### ISSUE TITLE
Run UI automation for every merge

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/sandbox#1002]
- Build demo components
- Install minukube cluster in ci environment
- Run UI automation tests

**Comment by novalina26** [comment]
Bukan berhenti saya ngak ngerti bos maaf ya bos saya benar benar ngk ngerti
dan anak juga nangis Krn bunyi ters hp maaf ya bos

Pada tanggal Kam, 6 Mei 2021 21.01, Rolson Quadras ***@***.***>
menulis:
