### ISSUE TITLE
Jobs fail to run after creation of sandbox

### ISSUE THREAD

**Issue by project-administrator** [trustbloc/sandbox#1072]
All of the jobs seem to be based on alpine image and all of them fail not being able to resolve the dl-cdn.alpinelinux.org:
```
Adding curl
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: DNS lookup error
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: DNS lookup error
ERROR: unable to select packages:
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
  curl (no such package):
    required by: world[curl]
/opt/vcs_governance_configure.sh: line 10: curl: not found
```

Not sure why this issue does not affect all other users, for now, I was able to reproduce it only on my system.  
More info in the upstream issue: https://github.com/gliderlabs/docker-alpine/issues/539

**Comment by alialkhalidi** [comment]
@project-administrator can we close this?
