### ISSUE TITLE
[Demo RP/Verifier] Verifiable Presentation (VP) validation page

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/sandbox#1275]
Add a new page in rp-rest:
- Display TrustBloc VCS Verifier URL
- Text box to paste Verifiable Presentation
- Checkbox to select validation options : proof (box checked) (in case of vc verification -> two boxes : proof and status)
- Button to send the request
- Once clicked display the result from VCS Verifier API

**Comment by mavarley** [comment]
Can the above functions also be supported via API call as well? Even if it is just an exposure of this page's "POST" call that results in loading our results page? That way a Mavennet or external page can POST data to us and we show our TB result page...

**Comment by rolsonquadras** [comment]
@mavarley We were thinking of invoking Verifier VC HTTP API directly from this page (using javascript axios library) - this new page being just a wrapper. The VC HTTP API is already available and can be invoked (curl or postman) using curl or postman.

**Comment by mavarley** [comment]
Oh, the validation options are already supported by the API? OK. So the POST would just return the HTTP API result and then render the credentials originally posted?

**Comment by mavarley** [comment]
Having a page that supports copy-paste and a visual rendering of the credential data (verified or not and the reason why a verification failed - expiry/revocation/signature...) would be a very useful demo/development tool.

We can worry about the "API" version another time, as it probably has less usefulness.

**Comment by rolsonquadras** [comment]
Ref to call backend api https://github.com/trustbloc/sandbox/blob/f8ef7e5d8c201c6b3235157ca30cca1619018f36/cmd/rp-rest/static/flightcheckinverify.html#L522-L546

 

>     let presentationData = {
>             "checks": ["proof"],
>             "domain" :<json_text_area>.proof.domain,
>             "challenge": <json_text_area>.proof.challenge,
>             "vp": <json_text_area>
>         };
> 
>         document.getElementById("loading-screen").style.display = "block";
>         axios.post('/verify/presentation',
>             presentationData
>         ).then(function (response) {
>        }
