### ISSUE TITLE
[oidc4vp] setup demo

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/sandbox#1391]
- [x] Add a new page to start the demo
- [x] Add API to handle UI request and invoke wallet auth endpoint
- [x] Add API to handle callback
- [x] success page
- [x] #1411 Finish Success Page loading

**Comment by talwinder50** [comment]
@rolsonquadras @sudeshrshetty 

Add a new page to start the demo for this are we simulating any existing rp demo page like open bank account etc or it can be anything like initiate oidc rp flow ?

**Comment by rolsonquadras** [comment]
@talwinder50 Let's consider PRCard use case. For WACI, we use `duty free shop` use case. May be for OIDC, we can have `background check` use case, ie, user need PR card to start background check.
