### ISSUE TITLE
Expose Gateway OpenAPI specification in sandbox

### ISSUE THREAD

**Issue by ypukhta** [trustbloc/sandbox#1502]
Sandbox need to expose an endpoint that would allow to retrieve OpenAPI specification for Gateway API. 
Supposed endpoint name - /openapi.json, format - JSON.
Making the API calls directly from that endpoint will not be supported in this iteration.

**Comment by mavarley** [comment]
It should be like the interactive display page, similar to what gets hosted when you do a ```make open-api-demo```.
Thanks.

**Comment by rolsonquadras** [comment]
OpenAPI link https://trustbloc.github.io/sandbox/
