### ISSUE TITLE
VaultServer Create Authorization API not supporting TrustBloc DID

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/sandbox#799]
Error while calling Vault Server `create-authorization` API 

`failed to create vault authorization: http request: failed to read response body for status 500: {"errMessage":"requesting party to DidURL: not a valid did:key identifier (not a base58btc multicodec): did:trustbloc:AiMP4:EiCUrP_33P0_sxJroDFtHVGmP5wdi_z-kL9PAoIwIJxPiA"}`

This is due to vault-server not supporting TrustBloc DID Method. The comparator creates the TrustBloc DID and this is used as "relyingparty" property in `create-authorization` API.

**Comment by soluchok** [comment]
@rolsonquadras it is done in https://github.com/trustbloc/edge-service/pull/633
FYI: requesting party should be like this `did:trustbloc:2M5ym:EiDL6JLccjj5-laF1KJjIiOGKlF2FRg5R0kl8CvNfvEPCw#893f6e66-09a4-4291-86e9-cab23bedaf52` where `#893f6e66-09a4-4291-86e9-cab23bedaf52` part is required

**Comment by rolsonquadras** [comment]
The RP DID comes from comparator config, which inturn comes from CSH. Currently, CSH supports only DID:KEY. Also, vault ID supports only DID:KEY.

**Comment by rolsonquadras** [comment]
This has been implemented.
