### ISSUE TITLE
k8s deployment - support to deploy images built locally

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/sandbox#963]
Currently, we are not able to deploy images built locally. In sandbox, we need the ability to make code changes, build the image locally, deploy with k8s and test without pushing to github.

> Error from server (BadRequest): container "login-consent" in pod "login-consent-54c94bd49f-lmw4f" is waiting to start: image can't be pulled

**Comment by alialkhalidi** [comment]
would this be an option? https://minikube.sigs.k8s.io/docs/handbook/registry/#docker-on-macos

**Comment by alialkhalidi** [comment]
so far, this what worked for me from the above, per container runtime(s):

**[crio]**

edit /etc/containers/registries.conf

[[registry]]
location="192.168.49.2:5000"
insecure=true


podman build -t $(minikube ip):5000/test-img:latest .
podman push --tls-verify=false $(minikube ip):5000/test-img:latest

**[docker]**

edit /etc/docker/daemon.json

{
"insecure-registries": ["192.168.49.2:5000"]
}

docker push  192.168.49.2:5000/test-img

for both, the end result is to have `image: 192.168.49.2:5000/test-img:latest` in the deployment, and per any of the component Makefiles:

make CSH_IMG=192.168.49.2:5000/csh:latest deploy

**Comment by rolsonquadras** [comment]
This has been completed.
